name: .NET CI/CD

on:
  push:
  branches: [ "develop", "main", "feature/*" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

       deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/tags/v*.*.*' # Solo se ejecuta si es un tag de releases

    steps:
    - name: Check out code
      uses: actions/checkout@v4

      - name: Run FTP deployment script
        run: |
          echo "Running FTP deployment script"
          powershell.exe -File .\deploy.ps1 -ftpServer "GestorDeTareas.somee.com" -ftpUsername "${{ secrets.FTP_USERNAME }}" -ftpPassword "${{ secrets.FTP_PASSWORD }}" -localPath "path/to/build/output" -remotePath "www.GestorDeTareas.somee.com"
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
