name: .NET CI/CD

on:
  push:
    branches:
      - develop
      - main
      - "feature/*"
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  deploy:
  name: Deploy to Production
  needs: build
  runs-on: ubuntu-latest
  if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Run FTP deployment script
      run: |
        echo "Running FTP deployment script"
        pwsh -File ./deploy.ps1 -ftpServer "GestorDeTareas.somee.com" -ftpUsername "${{ secrets.FTP_USERNAME }}" -ftpPassword "${{ secrets.FTP_PASSWORD }}" -localPath "path/to/build/output" -remotePath "www.GestorDeTareas.somee.com"
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
